# Generated by Django 3.0.8 on 2020-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200823_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateTimeField(default='1994-02-04'),
            preserve_default=False,
        ),
    ]
