# Generated by Django 3.0.8 on 2020-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='project_preferences',
            field=models.CharField(choices=[('Food Truck', 'Food Truck'), ('Restaurant', 'Restaurant'), ('Kitchen Gadgets', 'Kitchen Gadgets'), ('Food Products', 'Food Products'), ('Pop up Events', 'Pop up Events'), ('Food Tech Apps', 'Food Tech Apps'), ('Recipe Books', 'Recipe Books')], default='Restaurant', max_length=50),
        ),
    ]
