# Generated by Django 3.0.8 on 2020-08-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_project_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='project_preferences',
        ),
    ]
