# Generated by Django 3.0.8 on 2020-08-29 10:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200829_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_path),
        ),
    ]
