# Generated by Django 3.0.8 on 2020-08-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200829_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
