# Generated by Django 3.0.8 on 2020-09-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200830_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
