# Generated by Django 3.0.8 on 2020-09-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
    ]
