# Generated by Django 3.0.8 on 2020-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200823_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pledge',
        ),
    ]
