# Generated by Django 3.0.8 on 2020-08-23 06:18

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200823_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='campaign_end_date',
            field=models.DateTimeField(blank=True, default=projects.models.get_closing_date),
        ),
    ]
