# Generated by Django 3.0.8 on 2020-08-23 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200823_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 14, 21, 41, 620376)),
        ),
    ]
