# Generated by Django 3.0.8 on 2020-08-23 06:24

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200823_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='campaign_end_date',
            field=models.DateTimeField(default=projects.models.get_closing_date),
        ),
    ]
