# Generated by Django 3.0.8 on 2020-08-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200823_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('Food Truck', 'Food Truck'), ('Restaurant', 'Restaurant'), ('Kitchen Gadgets', 'Kitchen Gadgets'), ('Food Products', 'Food Products'), ('Pop up Events', 'Pop up Events'), ('Food Tech Apps', 'Food Tech Apps'), ('Recipe Books', 'Recipe Books')], default='Restaurant', max_length=50),
        ),
    ]
