# Generated by Django 3.0.8 on 2020-08-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_proj_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
