# Generated by Django 3.0.8 on 2020-08-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_category',
        ),
    ]
