# Generated by Django 3.0.8 on 2020-09-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20200830_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dream_goal_met',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
