# Generated by Django 3.0.8 on 2020-09-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_dream_goal_met'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dream_goal_met',
        ),
    ]
