# Generated by Django 3.0.8 on 2020-08-29 10:55

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_dream_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_path),
        ),
    ]
