# Generated by Django 3.0.8 on 2020-09-28 07:42

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20200901_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='campaign_end_date',
            field=models.DateField(default=projects.models.get_closing_date),
        ),
    ]
