# Generated by Django 3.0.8 on 2020-09-28 07:58

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200928_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='campaign_end_date',
            field=models.DateTimeField(default=projects.models.get_closing_date),
        ),
    ]
